"""Synthesize + place + route a design through OpenROAD-flow-scripts (ORFS) in docker.

Usage: python scripts/synth.py <design_dir> [--stage synth|floorplan|place|cts|route|final] [--json]

Generates an ORFS design config (config.mk + constraint.sdc) from design.yaml,
then runs the ORFS make flow with WORK_HOME pointed at a host-mounted build/
directory. Final output: build/results/<platform>/<design>/<variant>/<n>_final.gds

Exit codes: 0 = flow completed, 1 = flow failed, 2 = setup error.
"""

import argparse
import sys
from pathlib import Path

from _common import (
    ORFS_IMAGE,
    REPO_ROOT,
    ScriptError,
    add_common_args,
    docker_run,
    fail,
    load_design,
    output_result,
)

ORFS_FLOW_DIR = "/OpenROAD-flow-scripts/flow"
# generous full-flow runtime cap; intermediate stages finish well inside it
SYNTH_TIMEOUT_S = 3 * 60 * 60
# stage -> ORFS make target
STAGES = {
    "synth": "synth",
    "floorplan": "floorplan",
    "place": "place",
    "cts": "cts",
    "route": "route",
    "final": "final",
    "all": "final",
}

CONFIG_TEMPLATE = """# Generated by opensynth scripts/synth.py from design.yaml -- do not edit by hand.
export DESIGN_NAME      = {name}
export PLATFORM         = {platform}
export DESIGN_NICKNAME  = {name}
export VERILOG_FILES    = /work/design/rtl/{rtl_files}
export SDC_FILE         = /work/design/constraint.sdc
export CORE_UTILIZATION = {utilization}
export CORE_ASPECT_RATIO = {aspect_ratio}
export CORE_MARGIN      = {core_margin}
export PLACE_DENSITY    = {place_density}
# Kepler-formal (LEC/SEC) binaries in the ORFS image require AVX-512; the
# flow runs fine without them, so formal equivalence is disabled by default.
export LEC_CHECK = 0
export SEC_CHECK = 0
"""

SDC_TEMPLATE = """# Generated by opensynth scripts/synth.py from design.yaml -- do not edit by hand.
current_design {name}

set clk_name core_clock
set clk_port_name {clock_port}
set clk_period {clock_period}
set clk_io_pct 0.2

set clk_port [get_ports $clk_port_name]

create_clock -name $clk_name -period $clk_period $clk_port
set clk_io_name vclk_$clk_name
create_clock -name $clk_io_name -period $clk_period

set non_clock_inputs [all_inputs -no_clocks]

set_input_delay [expr $clk_period * $clk_io_pct] -clock $clk_io_name $non_clock_inputs
set_output_delay [expr $clk_period * $clk_io_pct] -clock $clk_io_name [all_outputs]
"""


def append_user_constraints(orfs_design_dir: Path, design_dir: Path) -> None:
    """Append <design_dir>/constraints.user.sdc (if present) to the generated SDC.

    Lets a design add second clocks, false paths, or I/O constraints that the
    generated template doesn't cover.
    """
    user = design_dir / "constraints.user.sdc"
    if user.exists():
        with open(orfs_design_dir / "constraint.sdc", "a", encoding="utf-8", newline="\n") as f:
            f.write("\n# --- user constraints (constraints.user.sdc) ---\n")
            f.write(user.read_text(encoding="utf-8").replace("\r\n", "\n"))


def main() -> int:
    parser = add_common_args(argparse.ArgumentParser(description=__doc__))
    parser.add_argument("--stage", choices=list(STAGES), default="final",
                        help="ORFS flow stage to run up to (default: final = full flow)")
    args = parser.parse_args()
    payload = {"stage": "synth-pnr", "design_dir": str(args.design_dir), "orfs_stage": args.stage}
    as_json = args.json

    try:
        spec = load_design(args.design_dir)
        d, t, a = spec.get("design", {}), spec.get("timing", {}), spec.get("area", {})
        name = d.get("name")
        if not name:
            raise ScriptError("design.name missing in design.yaml")
        platform = d.get("platform", "sky130hd")
        rtl_sources = d.get("rtl_sources", [])
        if not rtl_sources:
            raise ScriptError("design.rtl_sources missing/empty in design.yaml")

        build_dir = (args.design_dir / "build").resolve()
        orfs_design_dir = build_dir / "design"
        orfs_design_dir.mkdir(parents=True, exist_ok=True)
        rtl_dir = orfs_design_dir / "rtl"
        rtl_dir.mkdir(parents=True, exist_ok=True)

        # copy RTL into build/design/rtl
        import shutil
        for rel in rtl_sources:
            src = (args.design_dir / rel).resolve()
            if not src.exists():
                raise ScriptError(f"RTL source listed in design.yaml not found: {src}")
            shutil.copy2(src, rtl_dir / src.name)

        # generate constraint.sdc
        sdc = SDC_TEMPLATE.format(
            name=name,
            clock_port=t.get("clock_port", "clk"),
            clock_period=t.get("clock_period_ns", 10),
        )
        (orfs_design_dir / "constraint.sdc").write_bytes(sdc.replace("\r\n", "\n").encode("utf-8"))
        append_user_constraints(orfs_design_dir, args.design_dir)

        # generate config.mk (paths relative to ORFS flow dir; ./design is mounted)
        config = CONFIG_TEMPLATE.format(
            name=name,
            platform=platform,
            rtl_files=" ".join(f"{r.split('/')[-1]}" for r in rtl_sources),
            utilization=a.get("core_utilization", 45),
            aspect_ratio=a.get("core_aspect_ratio", 1),
            core_margin=a.get("core_margin", 2),
            place_density=a.get("place_density", 0.60),
        )
        (orfs_design_dir / "config.mk").write_bytes(config.replace("\r\n", "\n").encode("utf-8"))

        # small-die PDN: default sky130hd straps (met4/met5, 27um pitch) don't fit
        # cores under ~30um wide; use a met1-only grid instead
        import shutil as _shutil
        _shutil.copy2(REPO_ROOT / "scripts" / "pdn_small.tcl",
                      orfs_design_dir / "pdn.tcl")
        with open(orfs_design_dir / "config.mk", "a", encoding="utf-8", newline="\n") as f:
            f.write("export PDN_TCL = /work/design/pdn.tcl\n")
    except ScriptError as e:
        return fail(payload, str(e), as_json, exit_code=2)

    # ORFS make invocation; WORK_HOME=build/ keeps logs/results inside the mount.
    # Note: env.sh must be sourced from a login-style shell (-l) or the container's
    # ORFS_PATH setup; bash -c alone drops make's DESIGN_CONFIG on some invocations.
    make_cmd = (f"source /OpenROAD-flow-scripts/env.sh >/dev/null 2>&1; "
                f"cd {ORFS_FLOW_DIR} && "
                f"export SKIP_CTS_REPAIR_TIMING=1 LEC_CHECK=0 SEC_CHECK=0; "
                f"make DESIGN_CONFIG=/work/design/config.mk "
                f"WORK_HOME=/work {STAGES[args.stage]}")
    proc = docker_run(
        ORFS_IMAGE,
        mounts=[(build_dir, "/work")],
        cmd=["bash", "-lc", make_cmd],
        workdir=ORFS_FLOW_DIR,
        timeout=SYNTH_TIMEOUT_S,
    )

    log_tail = ((proc.stdout or "") + (proc.stderr or "")).strip().splitlines()[-60:]
    payload.update({
        "returncode": proc.returncode,
        "log_tail": log_tail,
    })

    gds = build_dir / "results" / platform / name / "base"
    final_gds = None
    if gds.exists():
        candidates = sorted(gds.glob("*final*.gds")) + sorted(gds.glob("*.gds"))
        if candidates:
            final_gds = str(candidates[0])
    payload["gds"] = final_gds

    # synth-only runs (or intermediate stages) legitimately have no GDS yet
    if proc.returncode == 0 and (final_gds or args.stage != "final"):
        payload["status"] = "pass"
        if final_gds:
            output_result(payload, as_json,
                          f"ORFS PASS: {name} on {platform} -> {final_gds}")
        else:
            output_result(payload, as_json,
                          f"ORFS PASS: {name} on {platform} completed stage '{args.stage}'")
        return 0

    payload["status"] = "fail"
    output_result(payload, as_json,
                  "ORFS FAIL (rc={}):\n".format(proc.returncode) + "\n".join(log_tail))
    return 1


if __name__ == "__main__":
    sys.exit(main())
